Axiomaticadi/playerdetailspagev2
davidpchi/toski pull request #24
Opened 2023-09-07 23:34 UTC by AxiomaticAdi

Created player details page containing minimal information

- Number of games played
- Win rate

Can access player details by clicking on row within /playerOverview page or URL manipulation

2023-09-07 23:48 UTC, davidpchi commented
Can you include a screen cap of the changes?

2023-09-07 23:49 UTC, davidpchi requested changes

2023-09-07 23:49 UTC, davidpchi commented on src/components/playerOverview/PlayerDetails.tsx
> +import { Flex, Heading, Text } from "@chakra-ui/react";
nit, this should go after all of the "react-..." dependencies. and then an empty line before any imports that come from the local project. 

If you could, please group together all "react-..." dependencies together.

2023-09-07 23:49 UTC, davidpchi commented on src/components/playerOverview/PlayerDetails.tsx
> +	// Key player variables
nit: avoid using the word "Key" here because it means something in react. "player variables" is sufficient

2023-09-07 23:49 UTC, davidpchi commented on src/components/playerOverview/PlayerDetails.tsx
> +	console.log(matches);
remove this :)

2023-09-07 23:55 UTC, AxiomaticAdi commented
<img width="822" alt="image" src="https://github.com/davidpchi/toski/assets/140542996/53e01dbc-f943-4ee8-b37c-ec1427632802">

Is this what you mean by screenshot of changes?

2023-09-08 00:12 UTC, davidpchi approved these changes

2023-09-08 00:55 UTC, merged